### PR TITLE
feat: add property to query curation by either dxDao or Kleros

### LINKED ISSUE #50: Create a property to query whether a market exists in DxDao or Kleros registry
Currently we have `curatedByDxDao` and `klerosTCRregistered`, and we'd like to query whether a market exists in at least one of them, but there's no 'or' operator in the graph query language. So we should have a property like `curatedByDxDaoOrKleros`.

### PR DESCRIPTION
**Pull request by mtsalenc**
Closes #50

### CODE REVIEW

**Review by KadenZipfel — APPROVED** [review]
LGTM

**Review by KadenZipfel — CHANGES_REQUESTED** [review]
It looks like `curatedByDxDaoOrKleros` and `klerosTCRregistered` haven't been added to the schema. Also we should add a test for this.

**Comment by mtsalenc** [comment]
> It looks like curatedByDxDaoOrKleros and klerosTCRregistered haven't been added to the schema.

What do you mean? They are at https://github.com/protofire/omen-subgraph/blob/b202cf185bf88d5ee89bb9123c18536205fd4480/schema.graphql#L142 and https://github.com/protofire/omen-subgraph/blob/b202cf185bf88d5ee89bb9123c18536205fd4480/schema.graphql#L144

**Comment by KadenZipfel** [comment]
> > It looks like curatedByDxDaoOrKleros and klerosTCRregistered haven't been added to the schema.
> 
> What do you mean? They are at
> 
> https://github.com/protofire/omen-subgraph/blob/b202cf185bf88d5ee89bb9123c18536205fd4480/schema.graphql#L142
> 
> and
> https://github.com/protofire/omen-subgraph/blob/b202cf185bf88d5ee89bb9123c18536205fd4480/schema.graphql#L144

My bad. I think my IDE just hadn't updated for some reason.

**Review by KadenZipfel — APPROVED** [review]

**Review by cag — COMMENTED** [review]
it gud

**Pull request merged**
